use crimes_em_chicago;
SELECT * FROM chicago_crime LIMIT 10;
SELECT * FROM chicago_crime;
SELECT count(ID) FROM chicago_crime WHERE ARREST is TRUE;
SELECT count(ARREST) AS quantidade FROM chicago_crime where ARREST = "TRUE";
SELECT distinct(LOCATION_DESCRIPTION), DESCRIPTION FROM chicago_crime;

SELECT * FROM census_data;
SELECT COMMUNITY_AREA_NAME FROM census_data where COMMUNITY_AREA_NAME like "B%";

SELECT * FROM chicago_public_schools;
SELECT COMMUNITY_AREA_NAME, COMMUNITY_AREA_NUMBER FROM chicago_public_schools where COMMUNITY_AREA_NUMBER between 10 and 15;
SELECT AVG(SAFETY_SCORE) FROM chicago_public_schools;
SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) FROM CHICAGO_PUBLIC_SCHOOLS GROUP BY COMMUNITY_AREA_NAME LIMIT 5;
SELECT COMMUNITY_AREA_NAME, SAFETY_SCORE FROM CHICAGO_PUBLIC_SCHOOLS WHERE SAFETY_SCORE = (SELECT min(SAFETY_SCORE) FROM CHICAGO_PUBLIC_SCHOOLS);
select A.PER_CAPITA_INCOME from CENSUS_DATA A, CHICAGO_PUBLIC_SCHOOLS B where A.COMMUNITY_AREA_NUMBER = B.COMMUNITY_AREA_NUMBER and B.SAFETY_SCORE = 1